services:
  # Service for the university-project application
  university-project:
    build: ./university-project/back
    container_name: university-project-back
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8002
    volumes:
      - ./university-project/back:/usr/src/app
    ports:
      - "8002:8002"
    env_file: .env
    restart: always
    depends_on:
      - university-project-db
    networks:
      - university-project-network

  redis:
    container_name: redis
    image: redis:7.2
    networks:
      - university-project-network
    ports:
      - 6389:6379
    restart: always
    volumes:
      - redis_data:/data

  # MongoDB for university-project
  university-project-db:
    image: mongo
    container_name: university-project-mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=university
    networks:
      - university-project-network
    volumes:
      - university-project-db-data:/data/db
    restart: always

  # Mongo Compass for database management
  mongo-compass:
    image: mongo-express
    container_name: mongo-compass
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@university-project-db:27017/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    depends_on:
      - university-project-db
    networks:
      - university-project-network
    restart: always

  # Service for the university-project front
  university-project-front:
    build: ./university-project/front
    container_name: university-project-front
    # command: "node .app/.output/server/index.mjs"
    working_dir: /usr/src/app
    volumes:
      - ./university-project/front:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.app/node_modules
      - /usr/src/app/.demo/node_modules
      - /usr/src/app/.app/.nuxt
      - /usr/src/app/.app/.output
      - /usr/src/app/.demo/.nuxt
    ports:
      - "80:3000"
    env_file: ./university-project/front/.app/.env
    depends_on:
      - university-project
      - university-project-db
    networks:
      - university-project-network
    restart: always

networks:
  university-project-network:
    driver: bridge

volumes:
  # Volume for university-project MongoDB data
  university-project-db-data:

  redis_data:

  # Volume for gpt database data
  gpt-db-data:
